---
- name: RDS  Creation
  hosts: all
  tasks:
  - name: RDS Creation
    rds:
      command: create
      instance_name: new-database
      db_engine: postgres
      region: us-east-1
      size: 10
      instance_type: db.m5.large
      username: mysql_admin
      password: 1nsecure
      tags:
        Environment: testing
        Application: cms
